### PR TITLE
Migrate to Resteasy Reactive

### PR DESCRIPTION
**Pull request by cardil**
Judging by the disclaimer on the page https://quarkus.io/guides/rest-client we should be switching to Reactive extensions, especially we want an event receiver in this project. Such an event receiver could benefit from reactive endpoint for the captured events.

### CODE REVIEW

**Comment by cardil** [comment]
I found a number of disparities between the `-reactive` RESTEasy and the classic one.

### Hibernate Validator doesn't like the `Valid` annotation on the interface, that's also used as a reactive REST client

The exception is: `javax.validation.ConstraintDeclarationException: HV000131: A method return value must not be marked for cascaded validation more than once in a class hierarchy, but the following two methods are marked as such: HelloResourceTestClient$$CDIWrapper#hello(String), HelloResource#hello(String)`

We can work around it, by https://github.com/cardil/openshift-knative-showcase/commit/c56f08afe419915b7a1438e33ed172a4ddd96995

But, I think this should be a bug, fixed in Quarkus. The classic RESTEasy works well with such a setup, and I feel the generated CDI class shouldn't be taken into validation here.

### Not a REST client without an empty `Path`

The exception is: `Not a REST client interface: interface com.redhat.openshift.knative.showcase.view.IndexResourceTestClient. No @Path annotation found on the class or any methods of the interface and no HTTP method annotations (@POST, @PUT, @GET, @HEAD, @DELETE, etc) found on any of the methods`

The non-reactive Rest client accepted such an interface properly. The reactive version requires us to put empty `@Path("")` on the interface.

See workaround: https://github.com/cardil/openshift-knative-showcase/commit/bbcfbb3d57d3dcdbab073c38f73e09cba6da281a

### The lack of UTF-8 encoding in the response's content-type header for HTML type

The Reactive version of the RESTEasy doesn't add encoding to the content type. Even, is explicitly stated in the interface.

Our unit test needs adjustments: https://github.com/cardil/openshift-knative-showcase/commit/faba1151e07f23c4030c3854c242e5fa61ddbb68

### The OpenAPI schema validation message change

The OpenAPI schema validation Exception thrown by reactive client has changed. The classic version of REST client has the message with a status code. The reactive client provides the failure cause in the message.

See adjustment: https://github.com/cardil/openshift-knative-showcase/commit/07475025be0325dc120a309bf8bc3f3559c74af3

### Can't use the `RestClientBuilder` in Quarkus integration tests

When using the classic REST client, it was possible to use it in the integration tests. Some basic implementation was provided, and worked with sensible default outside the container.

After changing the deps to the reactive version, I got an exception: `No RestClientBuilderResolver implementation found!`.

As a workaround, I used the RESTEasy core, and microprofile-client libraries in the test scope. That ensures an Arc free implementation in the IT tests. See: https://github.com/cardil/openshift-knative-showcase/commit/76d62f144b17d627f30aa06819f1ebe22ddf1fba

/hold

**Comment by cardil** [comment]
/cc @geoand

Pinging, as requested on Zulip thread: https://quarkusio.zulipchat.com/#narrow/stream/306418-resteasy-reactive/topic/Using.20your.20own.20REST.20interface.20as.20REST.20client.20in.20test

**Comment by geoand** [comment]
Also cc @Sgitario

**Comment by cardil** [comment]
I've reproduced those things in the Quarkus project. See: https://github.com/quarkusio/quarkus/pull/31361

**Comment by geoand** [comment]
👌

**Comment by cardil** [comment]
I've managed to find a workaround for using the `RestClientBuilder` in Quarkus integration tests. The solution is to use the RESTEasy core and microprofile-client in the test scope. That gives an implementation for `RestClientBuilder` that works without the Arc container.

This isn't ideal, as Quarkus RESTEasy Reactive should provide some default implementation when the Arc container isn't running.

**Review by pierDipi — APPROVED** [review]
Changes make sense to me, some changes could have been done separately (like moving and renaming things) but LGTM

/lgtm

**Pull request merged**
